**1)Write a NumPy program to get the numpy version and show numpy build configuration.**

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

**2)Write a NumPy program to get help on the add function.**

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**3)Write a NumPy program to test whether none of the elements of a given array is zero.**

In [ ]:
my_arr=[12,21,20,14,15,21,41]  
print(np.all(my_arr))

True


In [ ]:
my_arr=[12,21,0,20,14,15,21,41]  
print(np.all(my_arr))

False


**4)Write a NumPy program to test whether any of the elements of a given array is non-zero.**

In [ ]:
my_arr=[12,21,20,0,0,0,1,0,14,15,21,41]  
print(np.any(my_arr))

True


In [ ]:
my_arr=[0,0,0,0,0]  
print(np.any(my_arr))

False


**5)Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number). **

In [ ]:
a = np.array([1, 0, np.nan,21,40,np.inf])
print(np.isfinite(a))

[ True  True False  True  True False]


**6) Write a NumPy program to test element-wise for NaN of a given array.**

In [ ]:
a = np.array([1, 0, np.nan,21,40,np.inf])
print(np.isnan(a))

[False False  True False False False]


**8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.**

In [ ]:
a = np.array([1+1j, 1+0j,5+4j,3+2j,4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))



Original array
[1. +1.j 1. +0.j 5. +4.j 3. +2.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False  True  True False False False  True]


In [ ]:
print("Checking for real number:")
print(np.isreal(a))

Checking for real number:
[False  True False False  True  True  True False]


In [ ]:
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Checking for scalar type:
True
False


**9)Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.**

**10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.**

In [ ]:
x = np.array([15,45])
y = np.array([22,15])
print("Original numbers:")
print(x)
print(y)
print("add of two array")
print(np.add(x,y))
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[15 45]
[22 15]
add of two array
[37 60]
Comparison - greater
[False  True]
Comparison - greater_equal
[False  True]
Comparison - less
[ True False]
Comparison - less_equal
[ True False]


**11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays**

In [ ]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(x)
print(y)
print(np.add(x,y))
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))



[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
[ 144.        158.        170.        180.        300.       -270.
  240.        -20.        120.        200.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


**12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.**

In [ ]:
import numpy as np
my_arr=np.array([1, 7, 13, 105])
my_arr.size

4

In [ ]:
import numpy as np
my_arr1=np.array([1, 7, 13, 105])
print("Size of the array: ",my_arr1.size)
  
print("Memory size of one array element in bytes: ",my_arr1.itemsize)
  
# memory size of numpy array
print("Memory size of numpy array in bytes:",my_arr1.size * my_arr1.itemsize)

Size of the array:  4
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 32


**13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.**

In [ ]:
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr1=np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr2=np.ones(10)*5
arr2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**14. Write a NumPy program to create an array of the integers from 30 to70.**

In [ ]:
x=np.arange(30,71)
x

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

**15. Write a NumPy program to create an array of all the even integers from 30 to 70.**

In [ ]:
x=np.arange(30,71,2)
x

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

**16. Write a NumPy program to create a 3x3 identity matrix.**

In [ ]:
mat=np.identity(3)
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**17. Write a NumPy program to generate a random number between 0 and 1.**

In [ ]:
rand_number=np.random.normal(0,1,1)
rand_number

array([1.00777828])

**18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.**

In [ ]:
rand_number=np.random.normal(0,1,15)
rand_number

array([-1.06454503,  0.13621507, -0.67691853, -0.7793824 , -0.3391381 ,
       -0.75312661,  0.2327422 , -1.16292553, -0.29861129,  0.29965595,
       -0.66335496, -0.65103018,  0.09617679,  0.92608798,  0.33779006])

**19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.**

In [ ]:
x=np.arange(15,55)
print(x)
print("print all values except the first and last.0",x[1:-1])


[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
print all values except the first and last.0 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


**20. Write a NumPy program to create a 3X4 array using and iterate over it.**

In [ ]:
x=np.arange(9,21).reshape((3,4))
print(x)
for i in x:
  print(i,end=" ")

[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 9 10 11 12] [13 14 15 16] [17 18 19 20] 

In [ ]:
x=np.arange(9,21).reshape((3,4))
print(x)
for i in np.nditer(x):    ## nditer() function is to iterate an array of objects.converting a row into columns and columns into rows using “flags“
  print(i,end=" ")

[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
9 10 11 12 13 14 15 16 17 18 19 20 