In [ ]:
# list of integers, convert to numpy array, check its dtype, type
# list of decimals, convert to numpy array, check its dtype, type
# list of strings, convert to numpy array, check its dtype, type
# list of mixed data, convert to numpy array, check its dtype, type

In [ ]:
# list of integers, convert to numpy array, check its dtype, type
import numpy as np
list_1=[12,45,67,45,43,8,53]

a=np.array(list_1)
print(a)
a.dtype

[12 45 67 45 43  8 53]


dtype('int64')

In [ ]:
a.dtype


dtype('int64')

In [ ]:
list_1=[12.7,45.98,67.76,45.67,43.34,8,53.12]
b=np.array(list_1)
print(b)
b.dtype

[12.7  45.98 67.76 45.67 43.34  8.   53.12]


dtype('float64')

In [ ]:
list_1=["python","datascience","ML","Dl"]
c=np.array(list_1)
print(c)
c.dtype

['python' 'datascience' 'ML' 'Dl']


dtype('<U11')

In [ ]:
list_str = ["python","datascience","ML","Dl"]
arr_str = np.array(list_str)
print(arr_str.dtype)
print(type(arr_str))

<U11
<class 'numpy.ndarray'>


In [ ]:
list_4 = [15,56.52,98,(34,17),('a',(5,2)),["hi",['hello',"greetings"]],{"a":"apple"}]
d = np.array(list_4)
print(d.dtype)
print(type(d))


object
<class 'numpy.ndarray'>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [ ]:
int8 (8 bytes) : -127 to 128
int16 : -32767 to 32768
int32
int64
float16
float32
float64
uint8 : 0 to 255
uint16 : 0 to 65535
uint32
uint64
<U32

In [ ]:
np.array([132, 1,2], dtype = 'int8')## int8=-127 to 128(cal 2 power 8 = 256, 256/2 = 128,  -127........0.......128)

array([-124,    1,    2], dtype=int8)

In [ ]:
np.array([140, 1,2], dtype = 'int8')

array([-116,    1,    2], dtype=int8)

In [ ]:
gh = np.array([129])
gh.dtype

dtype('int64')

In [ ]:
gh = np.array([130])
gh.dtype

dtype('int64')

In [ ]:
np.array([129, 1,2], dtype = 'int16' )

array([129,   1,   2], dtype=int16)

In [ ]:
np.array([257, 1,2], dtype = 'uint8' )

array([1, 1, 2], dtype=uint8)

In [ ]:
np.array([256, 1,2], dtype = 'uint8' )

array([0, 1, 2], dtype=uint8)

In [ ]:
np.array([260, 1,2], dtype = 'uint8' )

array([4, 1, 2], dtype=uint8)

In [ ]:
def f(x):
  return x+10

if __name__ == "__main__":
  hg = int(input(" Enter an integer"))
  print(f(hg))

 Enter an integer42
52


In [ ]:
np.add(3,5)

8

In [ ]:
np.add(45,42)

87

In [ ]:
np.add([3,4],[5,6])

array([ 8, 10])

In [ ]:
np.add([3,4,6],[5,6])

ValueError: ignored

In [ ]:
np.add(np.array([1,2]), np.array([3,4]))

array([4, 6])

In [ ]:
l1 = [1,2]

In [ ]:
l1

[1, 2]

In [ ]:
np.array(l1)

array([1, 2])

In [ ]:
l3 = np.array([1,2,3,4])

In [ ]:
l3.size

4

In [ ]:
l3.shape #(2,) means 2 elements r there in this 1D Array

(4,)

In [ ]:
l3

array([1, 2, 3, 4])

In [ ]:
l3 = l3.reshape(4,1)


In [ ]:
l3

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
l4 = np.array([[[1,3,5],[2,4,6]], [[5,10,15],[20, 25, 30]]])

In [ ]:
l4

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 5, 10, 15],
        [20, 25, 30]]])

In [ ]:
ap = np.array([[1,2,3], [3,4,5]])
ap

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
ap.shape

(2, 3)

In [ ]:
l4

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 5, 10, 15],
        [20, 25, 30]]])

In [ ]:
l4.shape

(2, 2, 3)

In [ ]:
import numpy as np
y = np.array(  [[[[[[[[ 1,2 ]], [[ 1,2 ]]]], [[[[ 1,2 ]], [[ 1,2 ]]]], [[[[ 1,2 ]], [[ 1,2 ]]]]]]]]  )

In [ ]:
y

array([[[[[[[[1, 2]],

            [[1, 2]]]],



          [[[[1, 2]],

            [[1, 2]]]],



          [[[[1, 2]],

            [[1, 2]]]]]]]])

In [ ]:
y.shape

(1, 1, 1, 3, 1, 2, 1, 2)

In [ ]:
y.ndim

8

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [ ]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [ ]:
arr.shape

(1, 1, 1, 1, 4)

In [ ]:
import numpy as np

print(np.ones((4,5))*8)


[[8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]]


In [ ]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.eye(101))

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
print(np.eye(101,101))

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
print(np.arange(5,25))

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
print(np.arange(5,25,4))

[ 5  9 13 17 21]


In [ ]:
print(np.eye(4,4,2))

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.eye(4,4,3, dtype = 'int8'))

[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
import numpy as np

In [ ]:
list_1=[12,45,25,41,21]
a=np.array(list_1)
a

array([12, 45, 25, 41, 21])

In [ ]:
my_arr=np.array([12,145,25,41,21],np.int8)
my_arr

array([  12, -111,   25,   41,   21], dtype=int8)

In [ ]:
my_arr[0]

12

In [ ]:
my_arr[0,1]

IndexError: ignored

In [ ]:
my_arr=np.array([[12,145,25,41,21]],np.int8)

In [ ]:
my_arr[0]

array([  12, -111,   25,   41,   21], dtype=int8)

In [ ]:
my_arr[0,1]

-111

In [ ]:
my_arr.shape

(1, 5)

In [ ]:
my_arr.dtype

dtype('int8')

In [ ]:
## change element in numpy
my_arr[0,1]=45
my_arr

array([[12, 45, 25, 41, 21]], dtype=int8)

**Pandas**

In [1]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
list_1=[1,2,3,4,5,6]
l=pd.Series(list_1)

In [ ]:
l

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
type(l)

pandas.core.series.Series

In [ ]:
#index & data length shld match
pd.Series(list_1,index[])

Aus       1
Ind       2
pak       3
Nz        4
canada    5
swz       6
dtype: int64